##
## Jamn Personal Server Config Properties
##

#JPS Profile
jps.profile=app

#WebContentProvider files root folder
web.file.root=http

#Web File-Enricher root folder
web.file.enricher.root=http/jsmod/html-components

#JPS extension libraries root folder
jps.extension.root=extensions

#JPS workspace root folder
jps.workspace.root=workspace

#JPS Extension definition file name
jps.extension.def.file=app-extension-defs.json

#WebApp main Page
webapp.main.page=/workbench.html

#Extensions enabled
extensions.enabled=false

#JavaScriptProvider script root folder
script.root=scripts

#JavaScript auto-load script
js.auto.load.script=js-auto-load.js

#CLI enabled
cli.enabled=true

#JavaScript enabled
javascript.enabled=false

#JavaScript debug enabled
javascript.debug.enabled=false

#Server enabled
server.enabled=true

#WebService enabled
webservice.enabled=true

#WebSocket enabled
websocket.enabled=true

#WebSocket default url path
default.websocket.url.path=/wsoapi

#Child WebSocket default url path
default.child.websocket.url.path=/childapi

#JVM debug option
jvm.debug.option=-agentlib:jdwp=transport=dt_socket,address=localhost:9009,server=y,suspend=y

#Server autostart
server.autostart=true

#Child process debug
child.process.debug.enabled=false

#Standard encoding
standard.encoding=UTF-8

#Windows shell encoding
win.shell.encoding=Cp850

#Unix shell encoding
unix.shell.encoding=ISO8859_1

##
## JamnServer/0.0.1 Config Properties
##

#Server port
port=8099

#Max worker threads
worker=5

#Encoding
encoding=UTF-8

#Socket timeout in millis
client-socket-timeout=10000

#Cross origin flag
http-cors-enabled=false
