##
## Jamn Personal Server Config Properties
##

#JamnWebContentProvider files root folder
web.file.root=http

#Jamn Personal Server extension libraries root folder
jps.extension.root=extensions

#JPS Extension definition file name
jps.extension.def.file=app-extension-defs.json

#Extensions enabled
extensions.enabled=false

#JavaScriptExtension script root folder
script.root=scripts

#JavaScript auto-load script
js.auto.load.script=js-auto-load.js

#CLI enabled
cli.enabled=true

#JavaScript enabled
javascript.enabled=true

#JavaScript debug enabled
javascript.debug.enabled=false

#Server enabled
server.enabled=true

#Server autostart
server.autostart=true

#WebService enabled
webservice.enabled=true

#WebSocket enabled
websocket.enabled=true

#WebSocket default url path
default.websocket.url.path=/wsoapi

#Windows shell encoding
win.shell.encoding=Cp850

#Unix shell encoding
unix.shell.encoding=ISO8859_1

##
## JamnServer/0.0.1 Config Properties
##

#Server port
port=8099

#Max worker threads
worker=5

#Encoding
encoding=UTF-8

#Socket timeout in millis
client-socket-timeout=10000

#Cross origin flag
http-cors-enabled=false
